apiVersion: v1
kind:       Service
metadata:
  name: etcd
  labels:
    app.kubernetes.io/name: etcd
spec:
  ports:
    - port: 2380
      name: etcd-server
    - port: 2379
      name: etcd-client
  clusterIP:                None
  selector:
    app.kubernetes.io/name: etcd
  publishNotReadyAddresses: true