# Default values for stream-sum.
# This is a YAML-formatted file.

summer:
  replicaCount: 3

  image:
    repository: liveramp/gazette-examples
    binary: /go/bin/summer

chunker:
  numJobs: 10
  numStreams: 10000
  chunksPerStream: 100
