apiVersion: v1
kind:       Service
metadata:
  name: gazette
  labels:
    app.kubernetes.io/name: gazette
spec:
  type: ClusterIP
  ports:
    - port:       8080
      targetPort: http
      protocol:   TCP
      name:       http
  selector:
    app.kubernetes.io/name: gazette