apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "word-count.fullname" . }}-counter
  labels:
    app: {{ template "word-count.name" . }}-counter
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "word-count.name" . }}-counter
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-counter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [
            "/go/bin/run-consumer",
            "-config", "/etc/config/config.yaml",
          ]
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_ALLOCATORROOT
              value: "/examples/word-count/counter"
            - name: SERVICE_LOCALROUTEKEY
              value: "$(POD_IP):8080"
            - name: SERVICE_PLUGIN
              value: "/go/bin/counter.so"
          volumeMounts:
            - mountPath: /etc/config
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "word-count.fullname" . }}
