apiVersion: v1
kind:       Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app.kubernetes.io/name: postgres