name: Gazette Continuous Integration

on:
  push:
    branches: [arize, arize-dev/*]
  pull_request:
    branches: [arize]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history.

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: 'google-github-actions/auth@v1'
        with:
          token_format: "access_token"          
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: projects/${{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/github-actions
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: gcloud info

      - uses: actions/setup-go@v4
      - run: sudo apt install -y protobuf-compiler librocksdb-dev libsqlite3-dev etcd-server
      - run: echo "VERSION=0.99.0-arize-${sha:0:7}" >> "$GITHUB_ENV"

      - run: make go-test-ci
      - run: make go-build

      - uses: docker/build-push-action@v5
        with:
          context: .build
          file: Dockerfile
          target: broker
          platforms: linux/amd64
          tags: "${{ secrets.REGISTRY_PATH }}/gazette/broker:${{ env.VERSION }}"
          push: true
